pool:
  vmImage: 'windows-latest'

steps:    
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'
    
- script: DllExport -action Restore

- task: VSBuild@1
  inputs:
    solution: '**/*.sln'
    platform: 'Any CPU'
    configuration: 'Release'
    

# Get latest version of zpa-cli
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'z-plsql-analyzer'
    pipeline: 'zpa-cli'
    downloadType: 'single'
    artifactName: 'zpa-cli'
    itemPattern: 'zpa-cli/zpa-cli-shadow-*.zip'
    
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(System.ArtifactsDirectory)/**/*.zip' 
    destinationFolder: extracted

- template: package-and-publish.yaml
  parameters:
      platform: 'x86'
      name: '32-bit'
      
- template: package-and-publish.yaml
  parameters:
      platform: 'x64'
      name: '64-bit'